version: '3.5'
services:
  rabit_mq:
    image: rabbitmq:3-management
    container_name: rabitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
#    hostname: "rabbit1"
    ports:
      - "15672:15672"
      - "5672:5672"

